### ISSUE TITLE
Unable to query Zombieverter VCU parameters

### ISSUE THREAD

**Issue by davefiddes** [davefiddes/openinverter-can-tool#4]
[Reported by evMacGuyver](https://openinverter.org/forum/viewtopic.php?p=71950#p71950)

It seems that when trying to query the (Zombieverter VCU](https://github.com/damienmaguire/Stm32-vcu) OIC silently fails.

A SavvyCAN capture of the CAN traffic is attached.
[zombieverter-node3-query-paramdb.csv](https://github.com/user-attachments/files/15936174/zombieverter-node3-query-paramdb.csv)

It seems that the devices was running 2.17.A firmware.

**Comment by davefiddes** [comment]
It looks like oic fails with this error:
```
$ oic -d zombie.json listparams
Traceback (most recent call last):
  File "/home/dave/projects/model3-inverter/openinverter-can-tool/venv/bin/oic", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/dave/projects/model3-inverter/openinverter-can-tool/venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dave/projects/model3-inverter/openinverter-can-tool/venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/dave/projects/model3-inverter/openinverter-can-tool/venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dave/projects/model3-inverter/openinverter-can-tool/venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dave/projects/model3-inverter/openinverter-can-tool/venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dave/projects/model3-inverter/openinverter-can-tool/venv/lib/python3.12/site-packages/click/decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dave/projects/model3-inverter/openinverter-can-tool/venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dave/projects/model3-inverter/openinverter-can-tool/src/openinverter_can_tool/cli.py", line 63, in wrapper_db_action
    device_db = import_database(Path(cli_settings.database_path))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dave/projects/model3-inverter/openinverter-can-tool/src/openinverter_can_tool/paramdb.py", line 160, in import_database
    return import_database_json(doc)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dave/projects/model3-inverter/openinverter-can-tool/src/openinverter_can_tool/paramdb.py", line 122, in import_database_json
    values = {int(value): description for value, description in [
                                          ^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 2)
```
